### ISSUE TITLE
/ route doesn't include with Grunt connect

### ISSUE THREAD

**Issue by academo** [zeevl/connect-include#1]
Using Connect with grunt I access to my project index with some url like:

localhost:9000

When I use this URL the include doesn't work (just show the html comment), I must use

localhost:9000/index.html

and then It works.

I didn't test the issue with pure connect

Thanks for this great work!

**Comment by zeevl** [comment]
@jraller this was fixed in your PR, right?

**Comment by jraller** [comment]
I believe so.
